# This is file of the project INGONG
# Licensed under the MIT License.
# Copyright (c) 2025-2026 INGONG
# For full license text, see the LICENSE file in the root directory or at
# https://opensource.org/license/mit
# Author: Junho Kim
# Latest Updated Date: 2026-02-12

services:
  mysql:
    image: mysql:8.4
    container_name: inha_notice_mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - secret/mysql/.env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - inha_notice_network
  redis:
    image: redis:8.4.1-alpine
    container_name: inha_notice_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./volumes/redis:/data
    networks:
      - inha_notice_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  inha_notice_network:
    external: true
    name: inha_notice_network