# This is file of the project INGONG
# Licensed under the MIT License.
# Copyright (c) 2025 INGONG
# For full license text, see the LICENSE file in the root directory or at
# https://opensource.org/license/mit
# Author: Junho Kim
# Latest Updated Date: 2026-01-10

services:
  mysql:
    image: mysql:8.4
    container_name: inha_notice_mysql
    restart: unless-stopped
    ports:
      # Only DSM accessible
      - "127.0.0.1:3306:3306"
    env_file:
      - .env
    volumes:
      - ../volumes/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - PORT=3306 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - inha_notice_network

networks:
  inha_notice_network:
    external: true
    name: inha_notice_network